/** Known action/entityType strings written to AuditLog. The column itself
 * is a plain string (not a DB enum) so new action types don't need a
 * migration - these constants just keep call sites from hand-typing them. */
export const AuditAction = {
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_DELETED: "USER_DELETED",
  JOB_POSTING_CREATED: "JOB_POSTING_CREATED",
  JOB_POSTING_UPDATED: "JOB_POSTING_UPDATED",
  JOB_POSTING_DELETED: "JOB_POSTING_DELETED",
  APPLICATION_SIFTED: "APPLICATION_SIFTED",
  APPLICATION_EXAM_SCORES_IMPORTED: "APPLICATION_EXAM_SCORES_IMPORTED",
  APPLICATION_EXAM_SCORE_SET: "APPLICATION_EXAM_SCORE_SET",
  APPLICATION_SCHEDULED_INTERVIEW: "APPLICATION_SCHEDULED_INTERVIEW",
  CRITERION_CREATED: "CRITERION_CREATED",
  CRITERION_UPDATED: "CRITERION_UPDATED",
  CRITERION_DELETED: "CRITERION_DELETED",
  PANEL_ASSIGNED: "PANEL_ASSIGNED",
  PANEL_UNASSIGNED: "PANEL_UNASSIGNED",
  PANEL_EVALUATION_SUBMITTED: "PANEL_EVALUATION_SUBMITTED",
  POSITION_CREATED: "POSITION_CREATED",
  POSITION_UPDATED: "POSITION_UPDATED",
  POSITION_DELETED: "POSITION_DELETED",
} as const;

export const AuditEntityType = {
  USER: "User",
  JOB_POSTING: "JobPosting",
  APPLICATION: "Application",
  EVALUATION_CRITERION: "EvaluationCriterion",
  PANEL_ASSIGNMENT: "PanelAssignment",
  PANEL_EVALUATION: "PanelEvaluation",
  POSITION: "Position",
} as const;
