-- AlterTable
ALTER TABLE `applications` ADD COLUMN `rejectedAt` DATETIME(3) NULL,
    ADD COLUMN `rejectionRemarks` TEXT NULL,
    MODIFY `status` ENUM('SUBMITTED', 'UNDER_SIFTING', 'FOR_INTERVIEW', 'QUALIFIED', 'NOT_QUALIFIED', 'FOR_COMPLIANCE', 'NOT_SELECTED', 'DISQUALIFIED', 'FOR_OATH_TAKING', 'HIRED', 'WITHDRAWN') NOT NULL DEFAULT 'SUBMITTED';
