-- AlterTable
ALTER TABLE `documents` MODIFY `type` ENUM('APPLICATION_LETTER', 'PDS', 'IPCR', 'ELIGIBILITY_PROOF', 'LD_PROOF', 'TRANSCRIPT_OF_RECORDS', 'DIPLOMA', 'PQE_NOTICE', 'DESIGNATION_ORDER', 'AWARD_PROOF', 'OTHER') NOT NULL;
